Repository SMU-Capstone/server, pull requests merged in 2022-04, with the labels that each got.

#2 Swagger 기본 설정 및 관련 내용 작성
  package.json
  src/dto/trashcan/create-trashcan.dto.ts
  src/entities/Application.ts
  src/entities/Trashcan.ts
  src/main.ts
Labels: Setting, BACK, DB

#3 Docs: Add Yunho Yun's profile in README.md
  README.md
Labels: documentation

#4 Update README.md
  README.md
Labels: documentation

#6 Docs: API 명세서 작성
  src/dto/application/create-application.dto.ts
  src/dto/cleaning/create-cleaning.dto.ts
  src/entities/Application.ts
  src/entities/Cleaning.ts
Labels: documentation, BACK
