Repository SMU-Capstone/server, pull requests merged in 2022-05, with the labels that each got.

#7 Docs: README.md 업데이트
  README.md
Labels: documentation

#10 docs: README.md에 프로필 추가
  README.md
Labels: documentation

#11 Feat: 쓰레기통 관련 API 내용 작성
  src/domain/trashcan/trashcan.controller.ts
  src/domain/trashcan/trashcan.service.ts
  src/entities/Trashcan.ts
Labels: BACK, DB

#12 Fix: DB 테이블 설정 수정
  src/entities/Application.ts
  src/entities/Cleaning.ts
Labels: documentation, BACK, DB

#13 Fix: 올바르지 않은 Column name 수정
  src/domain/trashcan/trashcan.controller.ts
  src/domain/trashcan/trashcan.service.ts
  src/dto/trashcan/create-trashcan.dto.ts
  src/entities/Application.ts
  src/entities/Trashcan.ts
Labels: documentation, BACK, DB

#14 Chore: DB 수정 중 빠트린 변경사항 추가
  src/domain/application/application.controller.ts
  src/domain/cleaning/cleaning.controller.ts
  src/dto/application/create-application.dto.ts
Labels: bug, BACK

#16 Refactor: 메소드의 Return type 추가
  src/domain/cleaning/cleaning.controller.ts
  src/domain/cleaning/cleaning.service.ts
  src/domain/trashcan/trashcan.controller.ts
  src/domain/trashcan/trashcan.service.ts
Labels: BACK, refactor

#17 Fix: 범위 탐색 쿼리에 조건절 추가
  src/domain/trashcan/trashcan.controller.ts
  src/domain/trashcan/trashcan.service.ts
Labels: BACK
